python txt2binary.py d_bands_index_input.txt I
python txt2binary.py d_ht_pad_input.txt f
python txt2binary.py d_length1_input.txt I
python txt2binary.py d_outputdist_lookup_input.txt f
python txt2binary.py d_value2_input.txt I
python txt2binary.py d_Db_input.txt f
python txt2binary.py d_key1_input.txt I
python txt2binary.py d_length2_input.txt I
python txt2binary.py d_outputdist_output.txt f
python txt2binary.py d_ht_pad_codes_input.txt I 
python txt2binary.py d_key2_input.txt I
python txt2binary.py d_outputdist_input.txt f
python txt2binary.py d_value1_input.txt I
